### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by VideoGameSmash12** [allinkdev/Spigot-1.6.4-Docker#1]
1.6 is objectively one of the least interesting versions of Minecraft. It doesn't have a good logging system and most useful commands (like /summon, /setblock, etc) don't exist.

**Comment by allinkdev** [comment]
Survival.

**Comment by VideoGameSmash12** [comment]
I NEEEEEEEEEEEEEEEEEEEEEEEEEED TO REOPEN THIS ISSUE RIGHT NOW HOLY FRIGGING CRAP
